ansible/main.yml
New major release, might not be backward compatible. See release notes:
https://github.com/cloudfoundry/bosh-bootloader/releases
=> bosh bootloader to 4.0.0

ansible/main.yml
BUG FIXES:
* tools/terraform-bundle: Add missing Ui to ProviderInstaller (fix crash) (#15826)
* go-plugin: crash when server emits non-key-value JSON (go-plugin#43)
=> terraform to 0.10.2

ansible/main.yml
This reverts commit 6ead9705e6395a252aa4b65b614cc14b400797a0.
Looks like 1.1.3 was removed.
=> Revert "compliance masonry to 1.1.3"

ansible/roles/developer_packages/tasks/main.yml
IntelliJ can detect when the sources are present and it makes
navigating the code much nicer
=> Install Java source code

README.md, development-environment-base.json, http/base.seed
The atlas account name has been updated to use the finkit atlas
account. All references of developer-environment have been updated to
development-environment-base.
=> Renamed repository and atlas account references

ansible/roles/developer_packages/tasks/main.yml, ansible/roles/taurus/tasks/main.yml, development-environment-base.json
Added taurus ansible task
This ansible task installs all the pre-requisite python libraries required for taurus, along with the taurus python plugin. This allows taurus tests to be ran locally
=> Added taurus ansible task

ansible/main.yml, ansible/roles/developer_packages/tasks/main.yml
Removed the taurus task from developer_packages task list and added it
to main list
It was incorrectly added to the wrong file, which causes the packer build to fail
=> Moved taurus task to correct file

ansible/roles/intellij/tasks/main.yml
A specific location is required for community edition to ensure further
provisioning of base box, by installing ultimate for instance, can be
simplified.  This will also ensure that if further provisioning requires
community to be deleted, that it can be uniquely identified
=> Unique location for intellij community installation

ansible/roles/gcloud/tasks/main.yml
The latest release, 186.0.0, has known bugs. So hardcoding the previous
working version to ensure gcloud init works successfully.
=> Specify gcloud version to 185.0.0

ansible/roles/gcloud/tasks/main.yml
google-cloud-sdk 187.0.0 tested successfully so returning configuration to take latest release (as 186.0.0 was a bad release)
=> change google-cloud-sdk to latest version

ansible/roles/developer_packages/tasks/main.yml
This change enables installation of Python packages via pip. It has correct indentation for `become` parameter this time.
=> Install json2yaml package

ansible/roles/developer_packages/tasks/main.yml, ansible/roles/taurus/tasks/main.yml
In order to install json2yaml, we need python and python-pip packages installed
first. Removed them from `taurus` role and moved them into `developer_packages`
role.
=> Change installation order

development-environment-base.json
Without this, ansible cannot find the role config
=> Add json2yaml role definition

ansible/roles/bosh/tasks/main.yml
Ruby gem installation fails for ovirt-engine-sdk without it
=> Install libcurl

.travis.yml
As packer installer is downloaded directly, there's no need to update apt on each build
=> Remove apt update

ansible/roles/atom/tasks/main.yml
In preparation for ubuntu 18.04, myspell is superceded by hunspell. Both are compatible
=> Replace myspell with hunspell

development-environment-base.json
No longer retains artifacts of builds, and writes image to same file each time (which can be overwritten). Little value in retaining these files between builds
=> Clean up packer build box

development-environment-base.json
These were only so low due to building on hashicorp terraform. We can increase these as we build locally, which improves build speed
=> Increase packer build limits

ansible/roles/intellij/tasks/main.yml, ansible/roles/taurus/tasks/main.yml
No longer need to manually set the jdk version for intellij as the jre11 will not be present
=> Specify jdk version in taurus

ansible/roles/intellij/tasks/main.yml
Improves performance by making use of the custom openjdk that Jetbrains develop to run IntelliJ
=> Download intellij with the bundled JDK

ansible/main.yml
3.6.x has caused multiple issues in intellij and scala. Wait until some resolutions exist before updating
=> Rollback maven to 3.5.4

ansible/main.yml, ansible/roles/bash_alias/tasks/main.yml, ansible/roles/java/tasks/main.yml, ansible/roles/lightdm/files/lightdm.conf, ansible/roles/lightdm/tasks/main.yml, ansible/roles/pip_packages/tasks/main.yml, ansible/roles/power_management/files/.xscreensaver, ansible/roles/power_management/tasks/main.yml, ansible/roles/vi/files/vimrc, ansible/roles/vi/tasks/main.yml, ansible/roles/vscode/tasks/main.yml, development-environment-base.json
These were executed needlessly every time we provisioned
the private image. If they are moved to the base image
then the provision of the private image will be faster
and the public image will be better. The only problem
is that we now need to update the base image whenever
we change any of these roles.
=>  Move roles from private image to base

ansible/roles/vi/meta/main.yml
Links the fact that vi config relies on vi being installed and the config it sets for hub would need hub installed too
=> Add dependencies for vi role
