- ansible/main.yml
https://github.com/cloudfoundry/cli/releases
> cf-cli to 6.29.1

- ansible/main.yml
https://github.com/cloudfoundry/bosh-bootloader/releases
> bosh bootloader to 4.1.4

- ansible/main.yml
> Update atom cf-cli, intellij, postman, bosh-bootloader and golang

- ansible/main.yml
- update_github_projects.groovy
@edwardmlyte you may be interested in this.  I couldn't subscribe to other repos updates, but I could poll the releases.atom page and determine that there are updates.  Better than nothing eh?
> Added script to allow the autoupdating of github dependencies

- development-environment-base.json
I know we've been talking about it a lot before and there's enough opinions on both ends.
However, I am still bitten by the lack of disk space on the dev env on a weekly basis and, therefore, propose to give a try to a slight increase.
Let me know !
> Proposal to increase maximum disk size

- ansible/main.yml
Testing out to see if latest version has slowed down intellij.
https://youtrack.jetbrains.com/issue/IDEA-163509#comment=27-2530499
> Rollback maven to 3.5.0

- ansible/main.yml
Maven 3.5.2 is still very unresponsive in intellij at dependency
resolution
> Upgrade bosh bootloader, downgrade maven again

- ansible/main.yml
- ansible/roles/developer_packages/tasks/main.yml
- ansible/roles/groovy/tasks/main.yml
- development-environment-base.json
Install groovy instead of using older Ubuntu packaged version
> Install groovy

- ansible/roles/developer_packages/tasks/main.yml
Some people don't like vi. Who knew?!
> Add nano to dev packages

- ansible/main.yml
- update_github_projects.groovy
Invalid release in github. Going back to proper previous one
> Rollback yq_linux update

- ansible/roles/developer_packages/tasks/main.yml
This will allow us to use the glcoud kubernetes extensions within the dev env
> Added kubectl to the list of developer packages

- ansible/roles/developer_packages/tasks/main.yml
Adds a new task for installing json2yaml via pip module.
> Install json2yaml

- .travis.yml
Uses latest packer build for validation, and downloads from github URL
> Update to latest packer

- .travis.yml
add build (and subsequently upload) command to remove need for hashicorp terraform build
> add packer build command

- ansible/roles/hub/tasks/main.yml
This is less confusing for developers
> update hub to not be aliased over git command

- ansible/main.yml
- ansible/roles/intellij/tasks/main.yml
When packer is executed, the latest version of intellij is downloaded
> Automate intellij version lookup

- ansible/main.yml
Latest release on github isn't an actual release
> Downgrade bbl

- development-environment-base.json
Make it easier to edit and read
> Formatted base json

- ansible/roles/desktop/tasks/main.yml
- ansible/roles/developer_packages/tasks/main.yml
Gnome3 did not perform well, struggling with just IntelliJ running. Some customizations still need to be carried out (e.g. setting wallpaper, autologin)
> Switch to xubuntu

- ansible/roles/atom/tasks/main.yml
- ansible/roles/bosh/tasks/main.yml
- ansible/roles/cf_cli/tasks/main.yml
- ansible/roles/compliance_masonry/tasks/main.yml
- ansible/roles/credhub/tasks/main.yml
- ansible/roles/fly/tasks/main.yaml
- ansible/roles/go/tasks/main.yml
- ansible/roles/gradle/tasks/main.yml
- ansible/roles/groovy/tasks/main.yml
- ansible/roles/hub/tasks/main.yml
- ansible/roles/intellij/tasks/main.yml
- ansible/roles/json2yaml/tasks/main.yml
- ansible/roles/maven/tasks/main.yml
- ansible/roles/newrelic/tasks/main.yml
- ansible/roles/postman/tasks/main.yml
- ansible/roles/sts/tasks/main.yml
- ansible/roles/vscode/tasks/main.yml
Use colons to separate commands and values. Variables have spaces between the name and double braces. Value which contain a parameter need to be wrapped in quotes to run,
> Normalise ansible scripts

- ansible/roles/intellij/tasks/main.yml
- ansible/roles/postman/tasks/main.yml
- ansible/roles/sts/tasks/main.yml
It's one item in a loop. Pointless.
> Remove loops of one

- .gitignore
- README.md
- Vagrantfile
Replace the developer-environment repo with an internal Vagrantfile.
Updated the README to capture what the other repo explained.
> Add Vagrantfile

- ansible/main.yml
- ansible/roles/lastpass/tasks/main.yml
- development-environment-base.json
- update_github_projects.groovy
> Add lastpass CLI role

- scripts/build-and-upload.sh
Everyone doesn't have it in the same location
> Read repo location from env var

- ansible/main.yml
Looks like the newer version isn't a full release, so there is nothing to download
> Correct bbl version

- scripts/build-and-upload.sh
Helpful in debugging. Removed cleanup flag as it was set to the default value
> Add timestamp to packer output

- ansible/roles/vi/tasks/main.yml
It's doing one command, no need for unnecessary loop structure
> Remove single item lists

- ansible/main.yml
- ansible/roles/postman/tasks/main.yml
One less manual step.
Also tidied up tasks by removing unnecessary whitespace and quotes.
> Always download latest postman version

- .travis.yml
> Update packer to 1.3.3

- ansible/main.yml
> update cf-cli, vault and hub versions

- ansible/roles/intellij/tasks/main.yml
Jetbrains have recently changed the channel id for releases.
> Fix intellij installation

- ansible/main.yml
including cf-cli, gradle, golang, compliance masonry, vscode & hub
> update all the things
